# Generated by Django 6.0.1 on 2026-01-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_principal', models.ImageField(upload_to='apartamentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Indisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='apartamentos.apartamento')),
            ],
        ),
    ]
