# Generated by Django 6.0.1 on 2026-01-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indisponibilidade',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='apartamento.apartamento'),
        ),
    ]
