# Generated by Django 6.0.1 on 2026-01-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamento', '0002_alter_indisponibilidade_apartamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='ical_url',
            field=models.URLField(blank=True, verbose_name='Link do calendario (iCal)'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='link_anuncio',
            field=models.URLField(blank=True, verbose_name='Link do anuncio (airbnb)'),
        ),
    ]
