# Generated by Django 6.0.1 on 2026-01-28 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamento', '0003_apartamento_ical_url_apartamento_link_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='capacidade_hospedes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='FotoApartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='apartamentos/galeria/')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='apartamento.apartamento')),
            ],
        ),
    ]
