# Generated by Django 6.0.1 on 2026-01-28 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamento', '0004_apartamento_capacidade_hospedes_fotoapartamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='apartamentos/galeria')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='apartamento.apartamento')),
            ],
        ),
        migrations.DeleteModel(
            name='FotoApartamento',
        ),
    ]
