# Generated by Django 6.0.1 on 2026-01-28 00:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartamento', '0005_foto_delete_fotoapartamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='descricao',
            field=ckeditor.fields.RichTextField(verbose_name='Descricao Detalhada'),
        ),
    ]
